env: dev
payment_http:
  host: 0.0.0.0
  port: 9000
web_http:
  port: 8000
mysql:
    # 线上
    # uri: apollo:Apollo_2025_Pass!@tcp(127.0.0.1:3306)/jdcloudding?charset=utf8mb4&parseTime=True&loc=Local
    # win本地
    # uri: root:12345678@tcp(127.0.0.1:3306)/jdcloudding?charset=utf8mb4&parseTime=True&loc=Local
    # mac本地
    uri: root:abc123!!!@tcp(127.0.0.1:3306)/jdcloudding?charset=utf8mb4&parseTime=True&loc=Local
redis:
    addr: 127.0.0.1:6375
    password: ""
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

jcq:
  access_key: "your-ak"
  secret_key: "your-sk"
  topic: "your-topic"
  consumer_group_id: "your-consumer-group"
  http_url: "https://jcq-shared-004.cn-north-1.jdcloud.com"
  auto_ack: false
  poll_size: 5
  poll_interval_seconds: 1
